<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Inventory.BLL</RootNamespace>
    <AssemblyName>Inventory.BLL</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory.Common\Inventory.Common.csproj" />
    <ProjectReference Include="..\Inventory.DAL\Inventory.DAL.csproj" />
    <ProjectReference Include="..\Inventory.Entities\Inventory.Entities.csproj" />
    <ProjectReference Include="..\Inventory.Repository\Inventory.Repository.csproj" />
    <ProjectReference Include="..\Inventory.Services\Inventory.Services.csproj" />
  </ItemGroup>

</Project>
